apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.7.2
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.2
    spec:
      containers:
      - name: my-java-container
        image: maha4iac/mymahaapp:2
        ports:
        - containerPort: 8080

